export const FORM_PROJECT='FORM_PROJECT';
export const GET_PROJECTS='GET_PROJECTS';
export const ADD_PROJECT='ADD_PROJECT';
export const VALIDATE_FORM='VALIDATE_FORM';
export const PROJECT_ACTUAL="PROJECT_ACTUAL";
export const DELETE_PROJECT="DELETE_PROJECT";

export const TASK_PROJECT='TASK_PROJECT';
export const ADD_TASK='ADD_TASK';
export const VALIDATE_TASK='VALIDATE_TASK';
export const ELMINATE_TASK= 'ELMINATE_TASK';
export const STATE_TASK='STATE_TASK';
export const TASK_ACTUAL='TASK_ACTUAL';
export const UPDATE_TASK='UPDATE_TASK';
export const CLEAN_TASK='CLEAN_TASK';